AutoNet/AutoNet/Controllers/CarsController.cs
using AutoNet.Core.Domain;
using AutoNet.Core.Dto;
using AutoNet.Core.ServiceInterface;
using AutoNet.Data;
using AutoNet.Models.Cars;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoNet.Controllers
{
    public class CarsController : Controller
    {
        private readonly AutoNetContext _context;
        private readonly ICarsServices _carsServices;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IFileServices _fileServices;

        public CarsController
            (
            AutoNetContext context,
            ICarsServices carsServices,
            UserManager<ApplicationUser> userManager,
            IFileServices fileServices
            )
        {
            _context = context;
            _carsServices = carsServices;
            _userManager = userManager;
            _fileServices = fileServices;
        }

        public async Task<IActionResult> Index(int page = 1, int pageSize = 10)
        {
            pageSize = pageSize < 1 ? 10 : pageSize;

            var totalCars = await _context.Cars.CountAsync();

            var cars = await _context.Cars
                .Include(c => c.User)
                .Include(c => c.Files)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var result = cars.Select(car => new CarsIndexViewModel
            {
                Id = car.Id,
                Make = car.Make,
                Model = car.Model,
                Year = car.Year,
                VIN = car.VIN,
                Mileage = car.Mileage,
                Power = car.Power,
                EngineDisplacement = car.EngineDisplacement,
                Fuel = car.Fuel.ToString(),
                Transmission = car.Transmission.ToString(),
                Drivetrain = car.Drivetrain.ToString(),
                InspectionMonth = car.InspectionMonth,
                InspectionYear = car.InspectionYear,
                Price = car.Price,
                DiscountPrice = car.DiscountPrice,
                UserName = car.User != null ? car.User.UserName : "No User",
                Image = car.Files.FirstOrDefault() != null
                    ? new List<CarImageViewModel>
                        {
                    new CarImageViewModel
                    { 
                        Image = Convert.ToBase64String(car.Files.First().ImageData),
                        ImageTitle = car.Files.First().ImageTitle,
                        ImageId = car.Files.First().Id,
                        CarId = car.Files.First().CarId
                    }
                        }
                    : new List<CarImageViewModel>(),
                CreatedAt = car.CreatedAt,
                UpdatedAt = car.UpdatedAt
            }).ToList();

            var viewModel = new CarsIndexPaginationViewModel
            {
                Cars = result,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(totalCars / (double)pageSize),
                PageSize = pageSize
            };

            return View(viewModel);
        }



        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var car = await _context.Cars
                .Include(c => c.User)
                .Include(c => c.Files)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (car == null)
            {
                return View("Error");
            }

            var vm = new CarDetailsViewModel
            {
                Id = car.Id,
                Make = car.Make,
                Model = car.Model,
                Year = car.Year,
                VIN = car.VIN,
                Mileage = car.Mileage,
                Power = car.Power,
                EngineDisplacement = car.EngineDisplacement,
                Fuel = car.Fuel.ToString(),
                Transmission = car.Transmission.ToString(),
                Drivetrain = car.Drivetrain.ToString(),
                InspectionMonth = car.InspectionMonth,
                InspectionYear = car.InspectionYear,
                Description = car.Description,
                Price = car.Price,
                DiscountPrice = car.DiscountPrice,
                CreatedAt = car.CreatedAt,
                UpdatedAt = car.UpdatedAt,
                UserName = car.User?.UserName ?? "No User",
                UserFirstName = car.User?.FirstName ?? "No First Name",
                UserLastName = car.User?.LastName ?? "No Last Name",
                Images = car.Files.Select(file => new CarImageViewModel
                {
                    ImageId = file.Id,
                    CarId = file.CarId,
                    ImageTitle = file.ImageTitle,
                    Image = $"data:image/png;base64,{Convert.ToBase64String(file.ImageData)}"
                }).ToList()
            };

            return View(vm);
        }

        public async Task<IActionResult> UserCars()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var userCars = _context.Cars
                .Where(car => car.UserId == currentUser.Id)
                .Include(car => car.Files)
                .ToList();

            var vm = userCars.Select(car => new UserCarsViewModel
            {
                Id = car.Id,
                Make = car.Make,
                Model = car.Model,
                Year = car.Year,
                Fuel = car.Fuel.ToString(),
                Mileage = car.Mileage,
                EngineDisplacement = car.EngineDisplacement,
                Power = car.Power,
                Transmission = car.Transmission.ToString(),
                Drivetrain = car.Drivetrain.ToString(),
                Price = car.Price,
                DiscountPrice = car.DiscountPrice,
                UserName = currentUser.UserName,
                UserFirstName = currentUser.FirstName,
                UserLastName = currentUser.LastName,
                Image = car.Files.FirstOrDefault() != null
                    ? new CarImageViewModel
                    {
                        Image = Convert.ToBase64String(car.Files.First().ImageData),
                        ImageTitle = car.Files.First().ImageTitle,
                        ImageId = car.Files.First().Id,
                        CarId = car.Files.First().CarId
                    }
                    : null
            }).ToList();

            return View(vm);
        }


        [HttpGet]
        public IActionResult Create()
        {
            CarCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarCreateUpdateViewModel vm)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Unauthorized();
            }

            var dto = new CarDto()
            {
                Id = vm.Id,
                Make = vm.Make,
                Model = vm.Model,
                Year = vm.Year,
                VIN = vm.VIN,
                Mileage = vm.Mileage,
                Power = vm.Power,
                EngineDisplacement = vm.EngineDisplacement,
                Fuel = vm.Fuel.ToString(),
                Transmission = vm.Transmission.ToString(),
                Drivetrain = vm.Drivetrain.ToString(),
                InspectionMonth = vm.InspectionMonth,
                InspectionYear = vm.InspectionYear,
                Description = vm.Description,
                Price = vm.Price,
                DiscountPrice = vm.DiscountPrice,
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        CarId = vm.Id
                    }).ToArray()
            };

            var result = await _carsServices.Create(dto, currentUser.UserName);

            if (result == null)
            {
                ModelState.AddModelError(string.Empty, "Failed to create the car.");
                return View("CreateUpdate", vm);
            }

            return RedirectToAction(nameof(UserCars), vm);
        }


        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var userName = User.Identity.Name;
            var currentUser = await _userManager.FindByNameAsync(userName);

            if (currentUser == null)
            {
                return Unauthorized();
            }

			var car = await _carsServices.DetailAsync(id);

			if (car == null)
            {
                return NotFound();
            }

            if (car.UserId != currentUser.Id)
            {
                return Forbid();
            }

			var photos = await _context.FileToDatabases
				.Where(x => x.CarId == id)
				.Select(y => new CarImageViewModel
				{
					CarId = y.Id,
					ImageId = y.Id,
					ImageData = y.ImageData,
					ImageTitle = y.ImageTitle,
					Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
				}).ToArrayAsync();

            var vm = new CarCreateUpdateViewModel();

            vm.Id = car.Id;
            vm.Make = car.Make;
            vm.Model = car.Model;
            vm.Year = car.Year;
            vm.VIN = car.VIN;
            vm.Mileage = car.Mileage;
            vm.Power = car.Power;
            vm.EngineDisplacement = car.EngineDisplacement;
            vm.Fuel = car.Fuel.ToString();
            vm.Transmission = car.Transmission.ToString();
            vm.Drivetrain = car.Drivetrain.ToString();
            vm.InspectionMonth = car.InspectionMonth;

AutoNet/AutoNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<AutoNet.Core.Domain.ApplicationUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
    bool isLoginPage = ViewData["IsLoginPage"] != null && Convert.ToBoolean(ViewData["IsLoginPage"]);
    bool isRegisterPage = ViewData["IsRegisterPage"] != null && Convert.ToBoolean(ViewData["IsRegisterPage"]);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoNet.styles.css" asp-append-version="true" />
    <link rel="icon" href="/icons/carIcon.png" type="image/x-icon">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white px-5" asp-area="" asp-controller="Home" asp-action="Index">AutoNet</a>
                <div class="d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <div class="d-flex justify-content-center">
                                    <a class="nav-link text-dark me-2" href="#" data-bs-toggle="modal" data-bs-target="#accountModal">
                                        <i class="fa-solid fa-circle-user fa-2x text-white"></i>
                                    </a>
                                    <form asp-controller="Accounts" asp-action="Logout" method="post">
                                        <button type="submit" class="btn btn-logout">Logout</button>
                                    </form>
                                </div>
                            </li>
                        }
                        else
                        {
                            @if (!isLoginPage && !isRegisterPage)
                            {
                                <li class="nav-item">
                                    <div class="d-flex justify-content-center">
                                        <form asp-controller="Accounts" asp-action="Register" method="get" class="me-2">
                                            <button type="submit" class="btn btn-register">Register</button>
                                        </form>
                                        <form asp-controller="Accounts" asp-action="Login" method="get">
                                            <button type="submit" class="btn btn-login">Login</button>
                                        </form>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal fade" id="accountModal" tabindex="-1" aria-labelledby="accountModalLabel" aria-hidden="true">
        <div class="modal-dialog account-modal">
            <div class="modal-content">
                <div class="modal-header account-modal-header">
                    <h5 class="modal-title" id="accountModalLabel">Account</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body account-modal-body">
                    <div class="row">
                        <div class="col-2 d-flex justify-content-center align-items-center">
                            <p class="mb-0"><i class="fa-solid fa-circle-user fa-2x"></i></p>
                        </div>
                        <div class="col-10">
                            <p class="mb-0">@user?.FirstName @user?.LastName</p>
                            <p class="mb-2">@user?.Email</p>
                        </div>
                        <div class="col-12">
                            <a class="account-modal-link" asp-controller="Accounts" asp-action="ChangePassword">Change Password</a>
                        </div>
                    </div>
                    <hr />
                    <div class="col-12">
                        <a class="account-modal-link" asp-controller="Cars" asp-action="UserCars">My sale ads</a>
                        <a class="account-modal-link" asp-controller="Cars" asp-action="Create">Insert sale ad</a>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer text-muted">
        <div class="container d-flex justify-content-center">
            &copy; @DateTime.Now.Year - AutoNet - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="text-decoration: none; color: azure;"> Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function togglePasswordVisibility() {
            const passwordInput = document.getElementById("passwordInput");
            const toggleButton = document.querySelector(".toggle-password i");

            if (passwordInput.type === "password") {
                passwordInput.type = "text";
                toggleButton.classList.remove("bi-eye");
                toggleButton.classList.add("bi-eye-slash");
            } else {
                passwordInput.type = "password";
                toggleButton.classList.remove("bi-eye-slash");
                toggleButton.classList.add("bi-eye");
            }
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>